# Generated by Django 2.2.6 on 2019-11-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191107_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
