# Generated by Django 2.2.6 on 2019-11-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191108_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
