# Generated by Django 2.2.6 on 2019-12-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20191231_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='image',
            new_name='background',
        ),
    ]
